# Generated by Django 5.2.5 on 2025-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_num', models.CharField(max_length=6)),
                ('integrator_name', models.CharField(max_length=30)),
                ('object_name', models.TextField()),
                ('kop_name', models.CharField(choices=[('YEN', 'Юрченко Е.Н.'), ('NTT', 'Нагаев Т.Т.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
